### ISSUE TITLE
Retrieving the containerSelector & containerElement 

### ISSUE THREAD

**Issue by joacimnilsson** [RadiusNetworks/flybuy-js#3]
We rarely do searches in the DOM so in the current version I have the option to provide containerSelector which will then be used to search the DOM.

We already have the element so it would be better for us to provide the containerElement instead of the containerSelector.

If you want I can do a pull request.

My suggestion is that if containerSelector or just container is typeof "string" then search the DOM or if typeof "object" assume it's the element.

👨🏻‍💻

**Comment by greencoder** [comment]
Sounds good, I'll make that change next week so it can take either a selector or an element.
